# Generated by Django 5.2.1 on 2025-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('OWNER', 'Арендодатель'), ('RENTER', 'Арендатор'), ('USER', 'Гость')], default='USER', max_length=35),
        ),
    ]
