# Generated by Django 5.2 on 2025-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='extra_locat_city_ac5b06_idx'), models.Index(fields=['district'], name='extra_locat_distric_d512ec_idx'), models.Index(fields=['postal_code'], name='extra_locat_postal__8376b6_idx')],
                'unique_together': {('city', 'district', 'street', 'postal_code')},
            },
        ),
    ]
