# Generated by Django 5.2.1 on 2025-05-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
