# Generated by Django 5.2.1 on 2025-05-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255)),
                ('filters', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
