# Generated by Django 5.2.1 on 2025-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('REJECTED', 'Отклонено'), ('CANCELLED', 'Отменено'), ('cancelled_by_owner', 'Отменено арендодателем')], default='PENDING', max_length=20),
        ),
    ]
