# Generated by Django 5.2.1 on 2025-05-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_count', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(choices=[('STUDIO', 'Студия'), ('ONE_BEDROOM', 'Одна спальня'), ('TWO_BEDROOM', 'Две спальни'), ('TWO_BEDROOM_ENSUITE', 'Две спальни с отдельными ванными'), ('THREE_BEDROOM', 'Три спальни'), ('ENTIRE_HOUSE', 'Дом целиком'), ('COTTAGE', 'Коттедж'), ('PENTHOUSE', 'Пентхаус'), ('WG_ZIMMER', 'Комната в общей квартире (WG)'), ('SHARED_ROOM', 'Общая комната / койко-место'), ('LOFT', 'Лофт / Мансарда'), ('APARTMENT_WITH_TERRACE', 'Квартира с террасой/балконом')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extra.location')),
            ],
        ),
    ]
