# Generated by Django 5.2.1 on 2025-05-24 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['price'], name='offers_offe_price_65dd56_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['room_type'], name='offers_offe_room_ty_fc7884_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['rooms_count'], name='offers_offe_rooms_c_f378a8_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['location'], name='offers_offe_locatio_898099_idx'),
        ),
    ]
